name: dash_app
dependencies:
  - python=3.7
  - pip:
    - dash
    - dash-renderer
    - dash-core-components
    - dash-html-components
    - plotly
    - gunicorn
    - pandas
    - pandas_datareader
    - cufflinks